Orders should be also updated in ConvertProductsGenerator
B/c if you try to add product with price in EUR to order in another currency, you will get
  undefined method `+' for nil:NilClass
  spree/core/app/models/spree/line_item.rb:113:in `options='